enum RequestState {
  initialState,
  zakatLoading,
  zakatProductsLoading,
  productsLoading,
  getZakatProductsByKilosLoading,
  getZakatProductsByZakatIdLoading,
  getProductDataLoading,
  getUserDataLoading,
  //------------------
  zakatLoaded,
  zakatProductsLoaded,
  productsLoaded,
  getZakatProductsByKilosLoaded,
  getZakatProductsByZakatIdLoaded,
  getProductDataLoaded,
  getUserDataLoaded,
  //------------------
  zakatError,
  zakatProductsError,
  productsError,
  getZakatProductsByKilosError,
  getZakatProductsByZakatIdError,
  getProductDataError,
  getUserDataError,
  //------------------
  insertLoading,
  updateLoading,
  deleteLoading,
  //------------------
  insertDone,
  updateDone,
  deleteDone,
  //------------------
  insertError,
  updateError,
  deleteError,
  //------------------
  loginDone,
  loginError,
  loginLoading,
  //------------------
  logoutDone,
  logoutError,
  logoutLoading,
  //------------------
  registerDone,
  registerError,
  registerLoading,
}
